### ISSUE TITLE
XCode 12: The compiler is unable to type-check this expression in reasonable time

### ISSUE THREAD

**Issue by WesSouza** [Samasaur1/SwiftIP#12]
Trying to build my project fails on the library on this line:

```swift
// Check for running IPv4, IPv6 interfaces. Skip the loopback interface.
if (flags & (IFF_UP|IFF_RUNNING|IFF_LOOPBACK)) == (IFF_UP|IFF_RUNNING) {
```

Not sure what to do about this error:
> The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

Tested on iOS and visionOS.

**Comment by Samasaur1** [comment]
Hi @WesSouza! I think this is because my conditional compilation logic was wrong in #11 — I'm having some issues with the CI setup for this repository, but enough tests have passed that I'm going to merge my fixes.

**Comment by Samasaur1** [comment]
Go ahead and try it with v2.2.2 and let me know if it still isn't working!

**Comment by WesSouza** [comment]
It worked!

However, the result is incorrect: #14
